version: '3.8'
services:
  backend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - VERSION=${TAG:-2.0}
        - CACERT_LOCATION
      context: ./backend
      target: ${BUILD_TARGET:-dev}
    container_name: basegun-backend
    environment:
      - PATH_LOGS=/tmp/logs
      - OS_USERNAME
      - OS_PASSWORD
      - OS_PROJECT_NAME
      - http_proxy
      - https_proxy
      - UVICORN_LOG_LEVEL=${UVICORN_LOG_LEVEL}
      - LOG_LEVEL=${UVICORN_LOG_LEVEL}
      - no_proxy
      - WORKSPACE=dev
      - REQUESTS_CA_BUNDLE=$CACERT_LOCATION
    image: basegun-backend:${TAG:-2.0}-dev
    ports:
      - 8000:8000
    volumes:
      - $PWD/backend/src:/app/src
      - $PWD/backend/tests:/app/tests
      - $PWD/backend/logs:/tmp/logs
      - /app/src/weights

  frontend:
    build:
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - NODE_EXTRA_CA_CERTS=$CACERT_LOCATION
      context: ./frontend
      target: ${BUILD_TARGET:-dev}
    image: basegun-frontend:${TAG:-2.0}-dev
    container_name: basegun-frontend
    ports:
      - 8080:80 # if BUILD_TARGET = prod
      - 3000:5173
      # - 4173:4173 
    volumes:
      - $PWD/frontend/src:/app/src
      - /app/node_modules
