apiVersion: v1
kind: Service
metadata:
  name: basegun-frontend
  labels:
    {{- include "basegun.FrontLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.containerPort }}
  selector:
    {{- include "basegun.FrontSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: basegun-backend
  labels:
    {{- include "basegun.BackLabels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.containerPort }}
  selector:
    {{- include "basegun.BackSelectorLabels" . | nindent 4 }}
