# source https://cert-manager.io/docs/tutorials/acme/nginx-ingress/

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-preprod
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: basegun@interieur.gouv.fr
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-preprod
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx