name: Sync DSO gitlab repository

on:
  workflow_dispatch:
  push:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl "https://gitlab.apps.c6.numerique-interieur.com/api/v4/projects/193/trigger/pipeline" \
            -X POST \
            --fail \
            -F token=${{ secrets.DSO_TOKEN }} \
            -F ref=main \
            -F variables[GIT_BRANCH_DEPLOY]=${{ github.ref_name }} \
            -F variables[PROJECT_NAME]=app
