name: CI for preprod
on: workflow_dispatch
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the docker images
      run: make build-prod
    - name: Test running the docker containers
      run: |
        make up-prod
        ./infra/scripts/test-alive.sh localhost
        make down-prod
    - name: Login to GHCR
      if: success()
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push on GHCR
      if: success()
      run: |
        make push
        make push-develop
    - name: Delete untagged images
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ secrets.PERSO_ACCESS_TOKEN }}
        organization: datalab-mi
        container: basegun/basegun-backend
        dry-run: false
        prune-untagged: true
    - name: Delete untagged images
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ secrets.PERSO_ACCESS_TOKEN }}
        organization: datalab-mi
        container: basegun/basegun-frontend
        dry-run: false
        prune-untagged: true

  deploy-preprod:
    uses: ./.github/workflows/change-values-kube.yml
    needs: build-push
    with:
      branch: develop
      namespace: basegun-preprod
      domain: preprod.basegun.fr
    secrets:
      API_OVH_TOKEN: ${{ secrets.API_OVH_TOKEN }}
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_PROJECT_NAME: ${{ secrets.OS_PROJECT_NAME }}
      OS_USERNAME: ${{ secrets.OS_USERNAME }}
      X_OVH_TOKEN: ${{ secrets.PREPROD_OVH_TOKEN }}
      JOB_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.PREPROD_K8_CONFIG }}

  test:
    runs-on: ubuntu-latest
    needs: deploy-preprod
    steps:
      - uses: actions/checkout@v2
      - name: Test DNS
        if: success()
        run : |
          ./infra/scripts/test-alive.sh preprod.basegun.fr
