name: CI for prod deployment
on:
  push:
    tags:
      - 'v*'

jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish release
      uses: release-drafter/release-drafter@v5
      with:
        name: ${{ steps.get_version.outputs.VERSION }}
        tag: ${{ steps.get_version.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make build-prod
    - name: Test running the docker containers
      run: |
        make up-prod
        ./infra/scripts/test-alive.sh localhost
        make down-prod
    - name: Login to GHCR
      if: success()
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Push on GHCR
      if: success()
      run: |
        make push
        make push-latest
    - name: Delete untagged images
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ secrets.PERSO_ACCESS_TOKEN }}
        organization: datalab-mi
        container: basegun/basegun-backend
        dry-run: false
        untagged: true
    - name: Delete untagged images
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ secrets.PERSO_ACCESS_TOKEN }}
        organization: datalab-mi
        container: basegun/basegun-frontend
        dry-run: false
        untagged: true

  deploy-prod:
    uses: ./.github/workflows/change-values-kube.yml
    needs: build-push
    with:
      branch: main
      namespace: basegun-prod
      domain: basegun.fr
    secrets:
      API_OVH_TOKEN: ${{ secrets.API_OVH_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      JOB_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KUBECONFIG: ${{ secrets.PREPROD_K8_CONFIG }}
      X_OVH_TOKEN: ${{ secrets.PREPROD_OVH_TOKEN }}

  test:
    runs-on: ubuntu-latest
    needs: deploy-prod
    steps:
      - uses: actions/checkout@v2
      - name: Test DNS
        if: success()
        run : |
          ./infra/scripts/test-alive.sh basegun.fr